### ISSUE TITLE
Meet @ICCR

### ISSUE THREAD

**Issue by SimonBiggs** [hdclark/DICOMautomaton#1]
Hi @hdclark!

I saw your poster at ICCR. Are you here? It would be great to meet up.

Cheers,
Simon

**Comment by SimonBiggs** [comment]
@hdclark are you coming with the group?

**Comment by SimonBiggs** [comment]
@hdclark are you at the talks? Would you be in a position to come out... I have a brainwave...

**Comment by SimonBiggs** [comment]
(I'm just outside the talks)

**Comment by SimonBiggs** [comment]
I went into the talk, but if you do come, let me know.

**Comment by SimonBiggs** [comment]
Are you at the airport?

**Comment by hdclark** [comment]
No. I'm sticking around for MCMA. Was your flight delayed? I heard there
was an incident of some sort in the control tower.

**Comment by SimonBiggs** [comment]
Yeah, there was some sort of issue. I'm still at the airport. Will be
leaving at 8.30 on the morning... ... Just ... Trying... To.... Sleep.

**Comment by hdclark** [comment]
That's rough. At least you have the flight to get a bit more rest.
