### ISSUE TITLE
WASI

### ISSUE THREAD

**Issue by SimonBiggs** [hdclark/DICOMautomaton#2]
Heya @hdclark,

Not sure if you're aware of this. Here is an example of WASI usage:

https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md

And here is the library that uses WASI based builds to embed into Python libraries:

https://github.com/wasmerio/python-ext-wasm

Beautiful thing is, you can focus on Linux/POSIX and you get Windows compatibility for free... :).

**Comment by hdclark** [comment]
Thanks Simon!

The process is considerably more difficult when linking is required
(i.e., for multi-stage builds). DICOMautomaton relies on a number of
shared libraries -- both internal and external -- so targeting wasm
will probably require a large, dedicated toolchain to be created
before I can emit any usable wasm. C++ intrinsically presents other
challenges too, such as name mangling, which may require specific
compilation techniques or even source annotation (ala
https://developers.google.com/web/updates/2018/08/embind). Not
impossible, but a large undertaking.

In particular the CGAL library, which DICOMautomaton depends on,
requires specific compiler flags that are not (yet) supported for
wasm: https://github.com/WebAssembly/design/blob/master/FAQ.md#why-is-there-no-fast-math-mode-with-relaxed-floating-point-semantics
. There are quite a few hurdles at this point. I'm keeping an eye on
the efforts, but the developments could take some time. Maybe a GSOC
student or two.

**Comment by SimonBiggs** [comment]
Bumma really non the panacea we were going for.

**Comment by hdclark** [comment]
Not yet. I'm hopeful though. Cross-platform portability from POSIX-only
code is the dream. Docker and WSL don't quite offer the same appeal.

**Comment by SimonBiggs** [comment]
Certainly is the dream :)

**Comment by SimonBiggs** [comment]
Does the following look like some dream realisation has been occurring?

https://github.com/hdclark/DICOMautomaton#continuous-integration

**Comment by hdclark** [comment]
Indeed! Haven't ported everything yet, but the excellent MXE project made
short work of the bulk of the code.

I'm still unfortunately stuck on WASI, but hopefully I can progress by just
rewriting some of the problematic bits (e.g., SFML --> SDL).

**Comment by SimonBiggs** [comment]
That is awesome. I would highly recommend using a Windows VM within GitHub actions to run your tests on the build artefacts.

**Comment by hdclark** [comment]
I currently use Wine on GitLab. Have you experienced cases where Windows
proper was necessary? I'm rather inexperienced dealing with Windows.

**Comment by SimonBiggs** [comment]
You know what, that's probably good enough. There certainly are cases where it would fail in Wine, but not in Windows, but I can't think of a case where it would pass in Wine but fail in Windows. There might be something, but for now, the simplicity of being able to use Wine is likely worth the trade off.

**Comment by hdclark** [comment]
Well, regardless, thanks for the idea. I might set it up just in case
upstream (MXE) tests also use Wine and Wine ever diverges
significantly from Windows. I don't follow Windows developments, and
it seems like a lot if happening these days.

By the way I've recently tinkered with used ReactOS for testing
Windows binaries. It worked well, even for Windows 7 binaries, but
seemingly required a VM. Maybe another option if you lack licenses or
want to avoid proprietary software.

**Comment by SimonBiggs** [comment]
Ahh, I had not heard of ReactOS before. That certainly is an interesting approach. Might be worth setting up a VM of that on my local machine. It can be hard to check compatibility with just Ubuntu at home ...
