### ISSUE TITLE
Plausibility of including DICOMautomaton with PyMedPhys

### ISSUE THREAD

**Issue by SimonBiggs** [hdclark/DICOMautomaton#3]
Given the below discussion, might there be some plausibility of distributing DICOMautomaton with PyMedPhys?

Some references I have found on wrapping C++ code in a Python API is the following

* https://www.riverbankcomputing.com/software/sip/
* https://scikit-build.readthedocs.io/en/latest/
  * glue for CMake that [has cross compilation support](https://scikit-build.readthedocs.io/en/latest/usage.html)
* https://docs.python.org/3/extending/index.html
* https://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/c++-wrapping.html

It would certainly be great to be able to create a bridge that allows your work to be accessible in that way. Not sure how helpful I'd be... but more than happy to be as helpful as I can be :).

--------

> Indeed! Haven't ported everything yet, but the excellent MXE project made short work of the bulk of the code.
>
> I'm still unfortunately stuck on WASI, but hopefully I can progress by just rewriting some of the problematic bits (e.g., SFML --> SDL).

_Originally posted by @hdclark in https://github.com/hdclark/DICOMautomaton/issue_comments/708707028_

**Comment by hdclark** [comment]
Thanks Simon! I'll revisit the idea, especially if I can extract some subsets that are amenable to easy integration.

Lately I've been planning to use [SYCL](https://www.khronos.org/assets/uploads/developers/library/2017-supercomputing/SYCL-Compute-Cpp-Overview_Nov17.pdf) to make use of GPU and FPGA acceleration. This approach may require a customized compiler toolchain, but SYCL development is still in flux and some toolchains are more robust than others. Not sure if it is at all feasible to expose _SYCL-ized C++_ in this way though. Perhaps by maintaining custom python bindings? Many unknown unknowns still at this point...

**Comment by SimonBiggs** [comment]
Yeah, not too sure about what's plausible. But it certainly would be worth even just giving a single little subset an initial try so as to remove the friction to future Python bindings.

Regarding the GPU acceleration, I had been eyeing off https://github.com/google/jax for similar reasons. As my cogs are turning I think it might be the ideal platform for building a GPLed collapsed cone algorithm.
